### ISSUE TITLE
 model.Instances.New<IfcAlignment>() throwing null reference exception

### ISSUE THREAD

**Issue by WindingWinter** [xBimTeam/XbimEssentials#181]
I am testing with the latest `develop` branch

It seems that 
```
   using (var model = CreateandInitModel("Alignment model"))
    {
            using (var txn = model.BeginTransaction("Create alignment"))
            {

                var alignment = model.Instances.New<IfcAlignment>();
             }   
   }
```

Will throw at null reference exception at

> System.NullReferenceException was unhandled
>   HResult=-2147467261
>   Message=Object reference not set to an instance of an object.
>   Source=Xbim.IO
>   StackTrace:
>        at Xbim.IO.Memory.EntityCollection.AddReversible(IPersistEntity entity) in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.IO\Memory\EntityCollection.cs:line 259
>        at Xbim.IO.Memory.EntityCollection.New[T]() in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.IO\Memory\EntityCollection.cs:line 215
>        at InfrastructureExample.Program.CreateAlignment(IfcStore model, String name) in D:\.net Samples project\XbimSamples-master\XbimSamples-master\InfrastructureExample\Program.cs:line 253
>        at InfrastructureExample.Program.Main(String[] args) in D:\.net Samples project\XbimSamples-master\XbimSamples-master\InfrastructureExample\Program.cs:line 31
>        at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>        at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
>        at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>        at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>        at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>        at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>        at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>        at System.Threading.ThreadHelper.ThreadStart()
>   InnerException: 
> 

Can check?

If I initialize other IFC 4 entities like ` var site = model.Instances.New<IfcProductDefinitionShape>();`, there will be no such problem.

**Comment by martin1cerny** [comment]
You have to initialize the model with IFC4x1 schema to have access to IFC4x1 entities.

**Comment by martin1cerny** [comment]
But I agree the exception might be more helpful.

**Comment by WindingWinter** [comment]
OK, after I change the initialization to `IfcSchemaVersion.Ifc4x1`, I got another exception at 

```
System.Exception was unhandled
  HResult=-2146233088
  Message=This factory only creates types from its assembly
  Source=Xbim.Ifc4
  StackTrace:
       at Xbim.Ifc4.EntityFactoryIfc4x1.New(IModel model, Type t, Int32 entityLabel, Boolean activated) in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.Ifc4\EntityFactoryIfc4x1.cs:line 51
       at Xbim.Ifc4.EntityFactoryIfc4x1.New[T](IModel model, Int32 entityLabel, Boolean activated) in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.Ifc4\EntityFactoryIfc4x1.cs:line 36
       at Xbim.IO.Memory.EntityCollection.New[T]() in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.IO\Memory\EntityCollection.cs:line 213
       at Xbim.Ifc.IfcStore.get_OwnerHistoryAddObject() in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.Ifc\IfcStore.cs:line 730
       at Xbim.Ifc.IfcStore.IfcRootInit(IPersistEntity entity) in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.Ifc\IfcStore.cs:line 620
       at Xbim.Common.NewEntityHandler.Invoke(IPersistEntity entity)
       at Xbim.IO.Memory.MemoryModel.HandleEntityChange(ChangeType changeType, IPersistEntity entity, Int32 propertyOrder) in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.IO\Memory\MemoryModel.cs:line 336
       at Xbim.IO.Memory.Transaction.DoReversibleAction(Action doAction, Action undoAction, IPersistEntity entity, ChangeType changeType, Int32 propertyOrder) in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.IO\Memory\Transaction.cs:line 75
       at Xbim.IO.Memory.EntityCollection.AddReversible(IPersistEntity entity) in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.IO\Memory\EntityCollection.cs:line 279
       at Xbim.IO.Memory.EntityCollection.New[T]() in D:\.net Samples project\XbimEssentials-develop\XbimEssentials-develop\Xbim.IO\Memory\EntityCollection.cs:line 215
       at InfrastructureExample.Program.CreateandInitModel(String projectName) in D:\.net Samples project\XbimSamples-master\XbimSamples-master\InfrastructureExample\Program.cs:line 460
       at InfrastructureExample.Program.Main(String[] args) in D:\.net Samples project\XbimSamples-master\XbimSamples-master\InfrastructureExample\Program.cs:line 27
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```
This is my model initialization code:

```
        private static IfcStore CreateandInitModel(string projectName)
        {
            //first we need to set up some credentials for ownership of data in the new model
            var credentials = new XbimEditorCredentials
            {
                ApplicationDevelopersName = "Kodak LLC",
                ApplicationFullName = "Hello Civil Entity Application",
                ApplicationIdentifier = "Kodak LLC",
                ApplicationVersion = "1.0",
                EditorsFamilyName = "Team",
                EditorsGivenName = "xBIM",
                EditorsOrganisationName = "Kodak LLC"
            };
            //now we can create an IfcStore, it is in Ifc4 format and will be held in memory rather than in a database
            //database is normally better in performance terms if the model is large >50MB of Ifc or if robust transactions are required

            var model = IfcStore.Create(credentials, IfcSchemaVersion.Ifc4x1, XbimStoreType.InMemoryModel);

            //Begin a transaction as all changes to a model are ACID
            using (var txn = model.BeginTransaction("Initialise Model"))
            {

                //create a project
                var project = model.Instances.New<IfcProject>();
                //set the units to SI (mm and metres)
                project.Initialize(ProjectUnits.SIUnitsUK);
                project.Name = projectName;
                //now commit the changes, else they will be rolled back at the end of the scope of the using statement
                txn.Commit();
            }
            return model;

        }
```

By looking at the [`ifcstore` code](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.Ifc/IfcStore.cs#L720) I think it's pretty clear that the code is missing some ifc4x1 handling?



```
   public IIfcOwnerHistory OwnerHistoryAddObject
        {
            get
            {
                if (_ownerHistoryAddObject != null)
                    return _ownerHistoryAddObject;
                if (_schema == IfcSchemaVersion.Ifc4)
                {
                    var histAdd = Instances.New<Ifc4.UtilityResource.IfcOwnerHistory>();
                    histAdd.OwningUser = (Ifc4.ActorResource.IfcPersonAndOrganization)DefaultOwningUser;
                    histAdd.OwningApplication = (Ifc4.UtilityResource.IfcApplication)DefaultOwningApplication;
                    histAdd.ChangeAction = IfcChangeActionEnum.ADDED;
                    _ownerHistoryAddObject = histAdd;
                }
                else
                {
                    var histAdd = Instances.New<Ifc2x3.UtilityResource.IfcOwnerHistory>();
                    histAdd.OwningUser = (Ifc2x3.ActorResource.IfcPersonAndOrganization)DefaultOwningUser;
                    histAdd.OwningApplication = (Ifc2x3.UtilityResource.IfcApplication)DefaultOwningApplication;
                    histAdd.ChangeAction = Ifc2x3.UtilityResource.IfcChangeActionEnum.ADDED;
                    _ownerHistoryAddObject = histAdd;
                }
                return _ownerHistoryAddObject;
            }
        }

```

**Comment by martin1cerny** [comment]
Yes, you are right. I didn't try to create IFC4x1 from scratch and this is clearly a bug.

**Comment by martin1cerny** [comment]
Fixed now.

**Comment by WindingWinter** [comment]
Guess I have to resurrect this issue.

Despite that now `IfcAlignment `can now be instantiated, but        

`var clorthoid = model.Instances.New<IfcClothoidalArcSegment2D>();`

Still fails with the same null reference exception

I've checked, other two  cousin types `IfcLineSegment2D` and `IfcCircularArcSegment2D` can be instantiated, no problem.

**Comment by martin1cerny** [comment]
`IfcClothoidalArcSegment2D` has been removed from the final release. See the [change log](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/annex/annex-f/ifc4x1-final/changelog.htm). It is only left in xBIM as a legacy from previous code generation. I'm going to remove it so it doesn't confuse people.
